# ==============================================================================
# SCRIPT: 03_pre_imputation_check.R (MASTER VARIABLE STRUCTURE & AUDIT)
# ==============================================================================
library(data.table)

message("\n==================================================================")
message("🔍 RUNNING SCRIPT 03: MASTER VARIABLE STRUCTURE & AVAILABILITY AUDIT")
message("==================================================================")

# Ensure project root tracking is active
if (!requireNamespace("here", quietly = TRUE)) stop("CRITICAL: 'here' package missing.")

# ─── SECTION 1: ESTABLISH DATABASE CONTEXT & FILE INGESTION ───
DB_LABEL      <- "GOLD" # Toggle to "AURUM" as needed
is_aurum_mode <- (DB_LABEL == "AURUM")

# Dynamically link paths to the exact output generated by your previous script
input_checkpoint <- here::here(sprintf("staged_cohort_checkpoint_%s.rds", tolower(DB_LABEL)))

if (!file.exists(input_checkpoint)) {
  stop(paste("CRITICAL PIPELINE DEPENDENCY MISSING: Cannot find checkpoint file at:", input_checkpoint))
}

message("✔ Loading date-corrected cohort data...")
cohort_dt <- readRDS(input_checkpoint)

# Ensure absolute string compatibility for record indexing keys
cohort_dt[, patid := as.character(patid)]


# ─── SECTION 2: COVARIATE METRIC TRACKER DEFINITIONS ───
required_columns <- c("group", "patid", "case_patid", "bmi", "age_at_index", 
                      "smoking", "alcohol", "diabetes", "chronic_lung", 
                      "ethnicity", "imd_quintile", "is_urban")


# ─── SECTION 3: OPTIMIZED DATA MISSINGNESS ANALYSIS ───
missing_linkage_cols <- required_columns[!required_columns %in% names(cohort_dt)]
existing_cols        <- required_columns[required_columns %in% names(cohort_dt)]
total_records        <- nrow(cohort_dt)

message("⏳ Running fast vectorized matrix validation scan across variables...")

# High-speed data.table column profile scan utilizing optimized internal evaluations
missing_counts <- cohort_dt[, lapply(.SD, function(x) {
  sum(is.na(x) | x == "" | x == -9, na.rm = TRUE)
}), .SDcols = existing_cols]

# Transpose structural outcomes into an ordered, presentable reporting table
missing_summary <- data.table(
  Variable        = existing_cols,
  Missing_Count   = as.numeric(missing_counts[1, ]),
  Missing_Percent = round((as.numeric(missing_counts[1, ]) / total_records) * 100, 2)
)

message("\n📊 CURRENT DATA PROFILE (EXISTING CORE COVARIATES):")
print(missing_summary)


# ─── SECTION 4: HARDENED WORKSPACE ROUTING CONTROLLER ───
total_missing_cells <- sum(missing_summary$Missing_Count)
pipeline_decision   <- "RUN_PASS_THROUGH" # Default fallback setting

if (length(missing_linkage_cols) > 0) {
  pipeline_decision <- "RUN_TESTING_MODE"
  message("\n⚠️ DIAGNOSTIC NOTICE: Delayed linkage columns are currently absent from disk.")
  message("-> Strategy Applied: Activating 'RUN_TESTING_MODE' placeholder loops inside File 10.")
  
} else if (total_missing_cells > 0) {
  pipeline_decision <- "RUN_LIVE_IMPUTATION"
  message("\n🔄 DIAGNOSTIC NOTICE: Complete data frame present with active missing cells.")
  message("-> Strategy Applied: Routing workspace directly to live MICE multiple imputation loops.")
  
} else {
  message("\n✔ DIAGNOSTIC NOTICE: All master required variables are 100% populated on disk.")
  message("-> Strategy Applied: Routing data via direct analytical pass-through.")
}

# PERSIST ROUTING DECISION: Avoids volatile super-assignment operators (<<-)
# Writes configuration parameters out to a lightweight tracking record on disk 
routing_meta_path <- here::here(sprintf("pipeline_routing_config_%s.rds", tolower(DB_LABEL)))
saveRDS(list(PIPELINE_ROUTE = pipeline_decision), routing_meta_path)

# Save audit report dataset out for Airlock documentation review
fwrite(missing_summary, here::here(sprintf("DATA_QUALITY_MISSINGNESS_REPORT_%s.csv", DB_LABEL)))

# Clean memory maps
rm(cohort_dt, missing_summary, missing_counts)
gc(verbose = FALSE, full = TRUE)

message(sprintf("\n✔ [AUDIT COMPLETE]: Pipeline routing key configuration locked: '%s'", pipeline_decision))
message("==================================================================\n")
