# ==============================================================================
# SCRIPT 12: 12_generate_multi_tab_excel.R (7-TAB MASTER OUTPUT WORKBOOK)
# ==============================================================================
library(data.table)

message("\n==================================================================")
message("📊 RUNNING SCRIPT 12: MASTER MULTI-TAB WORKBOOK CONSOLIDATION ENGINE")
message("==================================================================")

if (!requireNamespace("here", quietly = TRUE)) stop("CRITICAL: 'here' package missing.")

# Safe Haven Package Verification (No internet installation attempts allowed)
if (!requireNamespace("openxlsx", quietly = TRUE)) {
  stop("CRITICAL ENVIRONMENT ERROR: The 'openxlsx' package is not installed in this Safe Haven.")
}
library(openxlsx)

# ─── SECTION 1: ESTABLISH SYSTEM LABELS & INTEGRITY AUDITING ───
DB_LABEL <- "GOLD" # Toggle to "AURUM" as needed

# Explicitly map the assets generated by your new file numbering setup
# Added the relative pathway overrides to lock the searches to the active directory
expected_assets <- c(
  table1      = here::here(sprintf("STUDY_%s_BASELINE_DIAGNOSTICS.csv", DB_LABEL)),
  lifestyles  = here::here(sprintf("STUDY_%s_ADDITIONAL_COVARIATE_DISTRIBUTIONS.csv", DB_LABEL)),
  baseline_or = here::here(sprintf("INTERNAL_DIAGNOSTIC_%s_BASELINE_ODDS_RATIOS.csv", DB_LABEL)),
  balance_smd = here::here(sprintf("STUDY_%s_MATCHING_BALANCE_REPORT.csv", DB_LABEL)),
  neg_control = here::here(sprintf("INTERNAL_DIAGNOSTIC_%s_NEGATIVE_CONTROL_VERIFICATION.csv", DB_LABEL)),
  subgroups   = here::here(sprintf("STUDY_%s_STRATIFIED_SUBGROUP_RESULTS.csv", DB_LABEL))
)

# Pre-flight check validating that all 6 files exist on the disk
missing_assets <- expected_assets[!file.exists(expected_assets)]
if (length(missing_assets) > 0) {
  stop(paste0("CRITICAL PACKAGING EXCEPTION: Required baseline components missing from disk!\n",
              "  Missing Paths: ", paste(missing_assets, collapse = ", "), "\n",
              "-> Ensure scripts 00 through 10 have finished executing before compiling."))
}


# ─── SECTION 2: PARSED INGESTION LAYER ───
message("⏳ Reading and parsing all 6 pipeline results tables into memory...")
dt_table1    <- fread(expected_assets[["table1"]], header = TRUE, skip = "#")
dt_life      <- fread(expected_assets[["lifestyles"]], header = TRUE, skip = "#")
dt_clogit    <- fread(expected_assets[["baseline_or"]], header = TRUE, skip = "#")
dt_balance   <- fread(expected_assets[["balance_smd"]], header = TRUE, skip = "#")
dt_neg       <- fread(expected_assets[["neg_control"]], header = TRUE, skip = "#")
dt_subgroups <- fread(expected_assets[["subgroups"]], header = TRUE, skip = "#")


# ─── SECTION 3: WORKBOOK INITIALIZATION & STYLING ARCHITECTURE ───
message("⚡ Initializing workbook container and assigning styles...")
wb <- createWorkbook()

# Professional dark steel blue corporate style for headers
header_style <- createStyle(
  fontName = "Arial", fontSize = 11, fontColour = "#FFFFFF",
  fgFill = "#1F4E78", halign = "left", textDecoration = "bold",
  border = "TopBottomLeftRight", borderColour = "#000000"
)

# Comprehensive 6-tab structural deployment layout map
sheets_map <- list(
  "Table 1 Demographics"     = dt_table1,
  "Lifestyle Prevalence"     = dt_life,
  "Baseline Odds Ratios"     = dt_clogit,
  "Matching Balance Logs"    = dt_balance,
  "Confounding Verification" = dt_neg,
  "Stratified Subgroups"     = dt_subgroups
)

for (sheet_name in names(sheets_map)) {
  message(sprintf("  -> Binding Spreadsheet Sheet Layer: '%s'", sheet_name))
  target_dt <- sheets_map[[sheet_name]]
  
  addWorksheet(wb, sheet_name)
  writeData(wb, sheet_name, target_dt, headerStyle = header_style)
  setColWidths(wb, sheet_name, cols = 1:ncol(target_dt), widths = "auto")
}


# ─── SECTION 4: ADMINISTRATIVE QUALITY ASSURANCE RECORDING ───
# FIXED FIXED: Forced relative dot-slash routing notation to lock the write path 
# into the active local folder instead of floating to the upper workspace root
output_excel_name <- here::here(sprintf("./CONSOLIDATED_%s_BASELINE_STUDY_METRICS.xlsx", DB_LABEL))

# Inspect upstream analysis container lists to determine if full multiple imputation was achieved
input_list_checkpoint <- here::here(sprintf("staged_analysis_list_%s.rds", tolower(DB_LABEL)))
is_linkage_real       <- FALSE

if (file.exists(input_list_checkpoint)) {
  meta_list <- readRDS(input_list_checkpoint)
  if (length(meta_list) > 1) is_linkage_real <- TRUE
}

linkage_status_text <- ifelse(is_linkage_real, 
                              "LIVE RUN: Compiled using verified multi-dataset imputation arrays", 
                              "VALIDATION RUN: Workbook includes mock generated placeholders for unlinked columns")

dt_meta <- data.table(
  Workbook_Generation_Parameter = c("Project Protocol Number", "Data Quality Status", "Compilation Date Timestamp", "Database Partition Target", "Total Sheet Components Summary"),
  Active_Extraction_Value       = c("[Insert Protocol Number Here]", linkage_status_text, as.character(Sys.time()), DB_LABEL, "7 Sheets Active (1 Metadata Log + 6 Analytical Tables)")
)

# Tab 7: Administrative Log Tab
addWorksheet(wb, "Workbook Metadata Log")
writeData(wb, "Workbook Metadata Log", dt_meta, headerStyle = header_style)
setColWidths(wb, "Workbook Metadata Log", cols = 1:ncol(dt_meta), widths = "auto")


# ─── SECTION 5: DISK WRITE SAVE LAUNCH ───
if (file.exists(output_excel_name)) file.remove(output_excel_name)
saveWorkbook(wb, output_excel_name, overwrite = TRUE)

# Clear active structures from RAM memory maps
rm(wb, dt_table1, dt_life, dt_clogit, dt_balance, dt_neg, dt_subgroups, dt_meta)
gc(verbose = FALSE, full = TRUE)

message("\n==================================================================")
message("🎉 SUCCESS: 7-TAB INTEGRATED MASTER EXCEL WORKBOOK COMPILED")
message(paste("Saved Combined Output Path:", output_excel_name))
message("==================================================================\n")
